#!/usr/bin/env python3
"""Snatcher content extraction pipeline (docs/plans/CONTENT_EXTRACTION.md).

    tools/content/extract.py <disc.cue> [--out extracted/content] [--stages iso,cdda,text,gfx-raw]

Writes extracted/content/<stage>/ (gitignored: it is game data), a manifest per stage, and REPORT.md for review.
"""
import argparse
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import stages  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("cue")
    ap.add_argument("--out", default="extracted/content")
    ap.add_argument("--stages", default=",".join(stages.STAGES))
    a = ap.parse_args()
    ctx = stages.Context(a.cue, a.out)
    os.makedirs(a.out, exist_ok=True)
    for name in a.stages.split(","):
        t0 = time.time()
        m = stages.STAGES[name](ctx)
        m["seconds"] = round(time.time() - t0, 1)
        json.dump(m, open(os.path.join(ctx.dir(name), "manifest.json"), "w"), indent=1)
        print(f"[{name}] {'verified' if m['verified'] else 'UNVERIFIED'} in {m['seconds']} s: {'; '.join(m['checks'])}")
    write_report(a.out)


def write_report(out):
    lines = ["# Snatcher content extraction report", "",
             "Generated by `tools/content/extract.py`. Game data: keep local, never commit or share.", "",
             "| Stage | Status | Checks | Review |", "|---|---|---|---|"]
    notes = []
    for name in stages.STAGES:
        p = os.path.join(out, name, "manifest.json")
        if not os.path.exists(p):
            lines.append(f"| {name} | not run | | |")
            continue
        m = json.load(open(p))
        review = " ".join(f"[{os.path.basename(r)}]({r})" for r in m["review"])
        lines.append(f"| {name} | {'✅ verified' if m['verified'] else '⚠️ unverified'} | {'<br>'.join(m['checks'])} | {review} |")
        notes += [f"- **{name}:** {n}" for n in m.get("notes", [])]
    lines += ["", "## Notes and open items", ""] + notes
    open(os.path.join(out, "REPORT.md"), "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
